spring:
  config:
    import: "optional:file:.env[.properties]"

  application:
    name: "IPillGood-server"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ipillgood}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity: 3600000
  refresh-token-validity: 1209600000
